Feature-96 MQTT support Implemented.
ScorpioBroker/ScorpioBroker pull request #100
Opened 2020-08-14 14:00 UTC by amitrnec

MQTT support pull request

2020-08-18 07:24 UTC, naveennec commented on Core/SubscriptionManager/src/main/resources/application.yml
> +query:
[Minor]indentation is not proper. it should be same as notification(above one) level.

2020-08-18 07:28 UTC, naveennec commented on Core/SubscriptionManager/src/main/java/eu/neclab/ngsildbroker/subscriptionmanager/service/BaseNotificationHandler.java
> +            Map<String,Object> mapObj = new HashMap<String, Object>();
[minor]Indentation is not proper

2020-08-18 07:36 UTC, naveennec commented on Commons/src/main/java/eu/neclab/ngsildbroker/commons/constants/NGSIConstants.java
> +	public static final String DEFAULT_MQTT_VERSION = "5";
[Major]Default version of MQTT should be "mqtt5.0" not 5.

2020-08-18 07:42 UTC, naveennec commented on Commons/src/main/java/eu/neclab/ngsildbroker/commons/constants/NGSIConstants.java
> +	public static final String DEFAULT_MQTT_QOS = "0";
[Suggestion] QOS is integer value why we are taking it as string as possible value of QOS is 0,1,2 so better to take it as Integer.

2020-08-18 07:44 UTC, naveennec commented on Commons/src/main/java/eu/neclab/ngsildbroker/commons/serialization/SubscriptionGsonAdapter.java
> +					Map<String,String> infoSettingNotifier = new HashMap<String,String>();
[Trival] Please write comment in the code for better understanding.

2020-08-18 07:45 UTC, naveennec commented on Commons/src/main/java/eu/neclab/ngsildbroker/commons/serialization/SubscriptionGsonAdapter.java
> +					} //else {
[Trival] please remove the commented section if this code is of no use.

2020-08-18 07:47 UTC, naveennec commented on Commons/src/main/java/eu/neclab/ngsildbroker/commons/serialization/SubscriptionGsonAdapter.java
> +				if (notification.getEndPoint().getNotifierInfo() != null) {
[Trival] Please write comment in the code for better understanding.

2020-08-18 07:48 UTC, naveennec commented on Commons/src/main/java/eu/neclab/ngsildbroker/commons/serialization/SubscriptionGsonAdapter.java
> +					 if(notification.getEndPoint().getNotifierInfo().get(NGSIConstants.MQTT_QOS) != null) {
[minor] indentation is not proper. Please correct it.

2020-08-18 07:50 UTC, naveennec commented on Commons/src/main/java/eu/neclab/ngsildbroker/commons/serialization/SubscriptionGsonAdapter.java
>  import java.util.Map.Entry;
[Minor] when Map is already imported then Map.Entry should be removed.

2020-08-18 07:56 UTC, naveennec commented on Core/SubscriptionManager/src/main/java/eu/neclab/ngsildbroker/subscriptionmanager/service/NotificationHandlerMQTT.java
>  				port = 1883;
[Query] the default MQTT port is 1883 for MQTT over TCP and 8883 for mqtts. Are we taking care of MQTTS

2020-08-26 08:34 UTC, ScorpioBroker approved these changes
LGTM

2020-08-27 06:00 UTC, naveennec requested changes

2020-08-29 12:17 UTC, merged