Hot fix for temporalValues
ScorpioBroker/ScorpioBroker pull request #164
Opened 2020-12-03 09:34 UTC by hiteshNEC

2020-12-05 04:54 UTC, amitrnec commented on History/HistoryManager/src/main/java/eu/neclab/ngsildbroker/historymanager/repository/HistoryDAO.java
> +			sqlQuery += "(select json_agg(jsonb_build_array(t -> '"+NGSIConstants.NGSI_LD_HAS_VALUE+"'->0->'" + NGSIConstants.JSON_LD_VALUE + "'"+",t->'https://uri.etsi.org/ngsi-ld/observedAt'->0->'@value'))
[Minor]Please "https://uri.etsi.org/ngsi-ld/observedAt" get from NGSIConstants same as other .

2020-12-05 04:54 UTC, amitrnec commented on History/HistoryManager/src/main/java/eu/neclab/ngsildbroker/historymanager/repository/HistoryDAO.java
> +			sqlQuery += "(select json_agg(jsonb_build_array(t -> '"+NGSIConstants.NGSI_LD_HAS_VALUE+"'->0->'" + NGSIConstants.JSON_LD_VALUE + "'"+",t->'https://uri.etsi.org/ngsi-ld/observedAt'->0->'@value'))
[Minor]Get "@value" from NGSIConstants also.

2020-12-07 09:57 UTC, ScorpioBroker requested changes
Hi,
yes please change the strings in general to the matching constants.
About the observedAt. This should be the time property from the query parameter here. observedAt is just the default (which qp should already handle if i recall right).

2020-12-07 14:10 UTC, hiteshNEC commented
> Hi,
> yes please change the strings in general to the matching constants.
> About the observedAt. This should be the time property from the query parameter here. observedAt is just the default (which qp should already handle if i recall right).

2020-12-08 09:06 UTC, amitrnec approved these changes

2020-12-08 09:47 UTC, hiteshNEC commented
> yes please change the strings in general to the matching constants.
Done
> About the observedAt. This should be the time property from the query parameter here. observedAt is just the default (which qp should already handle if i recall right).
According to the spec section C.5.6, we have to return value with their observedAt.

2020-12-09 09:27 UTC, ScorpioBroker commented
@hiteshNEC C5.6 shows an example where no temporalproperty is provided and hence defaults to observedAt. Please check 4.11 for more details on that.

2020-12-18 10:53 UTC, ScorpioBroker approved these changes
lgtm

2020-12-18 11:08 UTC, merged