Bugfix 162
ScorpioBroker/ScorpioBroker pull request #176
Opened 2020-12-22 09:10 UTC by hiteshNEC

2020-12-23 03:56 UTC, amitrnec commented on Commons/src/main/java/eu/neclab/ngsildbroker/commons/datatypes/QueryTerm.java
> +			attributeFilterProperty.append(" in (select jsonb_array_elements("+charcount+"->'https://uri.etsi.org/ngsi-ld/hasValue')->>'@value'))");
[Minor] please change the strings in general to the matching constants as "hasValue" and' @value'.

2020-12-23 06:47 UTC, amitrnec approved these changes

2021-01-13 08:47 UTC, ScorpioBroker requested changes
Hi,
this introduces a bad grammar sql exception on the query tests. Please check your query.

org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [SELECT data_without_sysattrs as data FROM entity WHERE type = 'https://uri.etsi.org/ngsi-ld/default-context/T_Query' AND (EXISTS (SELECT FROM jsonb_array_elements(data#>'{https://uri.etsi.org/ngsi-ld/default-context/P100}') as a WHERE EXISTS (SELECT FROM jsonb_array_elements(a#>'{https://uri.etsi.org/ngsi-ld/default-context/P1_P1}') as b WHERE (b#> '{https://uri.etsi.org/ngsi-ld/hasValue,0,@value}') > '0.70'::jsonb OR (0.70 in (select jsonb_array_elements(b->'https://uri.etsi.org/ngsi-ld/hasValue')->>'@value')) OR (b#> '{@value}') > '0.70'::jsonb))) AND  1=1 LIMIT 50 OFFSET 0 ]; nested exception is org.postgresql.util.PSQLException: ERROR: operator does not exist: numeric = text
  Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
  Position: 429

2021-01-15 11:29 UTC, amitrnec commented
> Hi,
> this introduces a bad grammar sql exception on the query tests. Please check your query.
> 
> org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [SELECT data_without_sysattrs as data FROM entity WHERE type = 'https://uri.etsi.org/ngsi-ld/default-context/T_Query' AND (EXISTS (SELECT FROM jsonb_array_elements(data#>'{https://uri.etsi.org/ngsi-ld/default-context/P100}') as a WHERE EXISTS (SELECT FROM jsonb_array_elements(a#>'{https://uri.etsi.org/ngsi-ld/default-context/P1_P1}') as b WHERE (b#> '{https://uri.etsi.org/ngsi-ld/hasValue,0,@value}') > '0.70'::jsonb OR (0.70 in (select jsonb_array_elements(b->'https://uri.etsi.org/ngsi-ld/hasValue')->>'@value')) OR (b#> '{@value}') > '0.70'::jsonb))) AND 1=1 LIMIT 50 OFFSET 0 ]; nested exception is org.postgresql.util.PSQLException: ERROR: operator does not exist: numeric = text
> Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
> Position: 429

Done

2021-01-21 14:14 UTC, ScorpioBroker approved these changes
Adresses the original issue and further list handling.

2021-01-21 14:14 UTC, merged