Resolved issue 237
ScorpioBroker/ScorpioBroker pull request #238
Opened 2021-09-02 06:15 UTC by pawannec

2021-09-02 06:24 UTC, amitrnec approved these changes

2021-10-22 10:35 UTC, RupamNEC approved these changes

2021-10-27 08:02 UTC, ScorpioBroker requested changes
Hi,

this still doesn't work on normal append 
patch on
http://localhost:9090/ngsi-ld/v1/entities/urn:ngsi-ld:Vehicle:A100/attrs/
{"brandName": {
    "value": "123asdasd5asd67",
    "type": "Property"
}
}
does still trigger the notification where it shouldn't.

2021-10-27 08:02 UTC, ScorpioBroker commented on Commons/src/main/java/eu/neclab/ngsildbroker/commons/datatypes/EntityRequest.java
> +	protected String updAttrName;
remove and save the original payload / construct it on partial update
original payload in the given example on general update/append would be 
{"brandName": {
    "value": "BMW",
    "type": "Property"
}
}
on partial it's only
{
    "value": "BMW",
    "type": "Property"
}
but you can construct it in this case.

2021-10-27 08:02 UTC, ScorpioBroker commented on Commons/src/main/java/eu/neclab/ngsildbroker/commons/serialization/EntityRequestGsonAdapter.java
> +			} else if (entry.getKey().equals(AppConstants.REQUEST_UPD_ATTR_NAME)) {
remove and forward original payload instead

2021-10-27 08:02 UTC, ScorpioBroker commented on Core/SubscriptionManager/src/main/java/eu/neclab/ngsildbroker/subscriptionmanager/service/SubscriptionService.java
> +		update.setAttrname(updateRequest.getUpdAttrName());
remove and change line 859 to take the original payload and do the same for append

2021-10-27 08:02 UTC, ScorpioBroker commented on Core/SubscriptionManager/src/main/java/eu/neclab/ngsildbroker/subscriptionmanager/service/SubscriptionService.java
> +
remove entire block ... not needed when the proper original payload/delta entity is given here.

2021-10-29 16:13 UTC, ScorpioBroker approved these changes

2021-10-29 18:40 UTC, merged