Implement csource registration limit and fix query related issue.
ScorpioBroker/ScorpioBroker pull request #247
Opened 2021-10-21 08:02 UTC by amitrnec

2021-10-27 09:07 UTC, ScorpioBroker requested changes
Hi, looks in general good to me but please add the offset parameter directly as well to have a complete pagination feature here. 
Thanks

2021-10-27 12:29 UTC, ScorpioBroker requested changes

2021-10-27 12:29 UTC, ScorpioBroker commented on Registry/RegistryManager/src/main/java/eu/neclab/ngsildbroker/registryhandler/controller/RegistryController.java
> +	private static String generateFollowUpLinkHeader(HttpServletRequest request, int offset, int limit, String token,
Hi,

as discussed no copy pasta, please move the private static you copied from the query controller into HttpUtils in commons and let the reg controller and the query controller use the common static method

2021-10-27 14:25 UTC, amitrnec commented on Registry/RegistryManager/src/main/java/eu/neclab/ngsildbroker/registryhandler/controller/RegistryController.java
> +	private static String generateFollowUpLinkHeader(HttpServletRequest request, int offset, int limit, String token,
Done

2021-10-28 08:20 UTC, ScorpioBroker approved these changes

2021-10-28 10:54 UTC, RupamNEC approved these changes

2021-10-28 11:01 UTC, merged