Fixed issue no 309
ScorpioBroker/ScorpioBroker pull request #314
Opened 2022-06-17 07:24 UTC by pawannec

Fixed issue no 309

2022-06-17 08:07 UTC, amitrnec commented on Commons/src/main/java/eu/neclab/ngsildbroker/commons/tools/EntityTools.java
> +		if(subscription.getSubscription().getNotification().getAttributeNames() == null || subscription.getSubscription().getNotification().getAttributeNames().isEmpty()) {
[Minor] Please take in List<String> and then compare null and isEmpty.

2022-06-17 08:17 UTC, pawannec commented on Commons/src/main/java/eu/neclab/ngsildbroker/commons/tools/EntityTools.java
> +		if(subscription.getSubscription().getNotification().getAttributeNames() == null || subscription.getSubscription().getNotification().getAttributeNames().isEmpty()) {
Done

2022-06-29 14:06 UTC, ScorpioBroker requested changes

2022-06-29 14:06 UTC, ScorpioBroker commented on Commons/src/main/java/eu/neclab/ngsildbroker/commons/tools/EntityTools.java
> +		List<String> notifucationAttrs = subscription.getSubscription().getNotification().getAttributeNames();
[minor] typo "notification"

2022-06-29 14:06 UTC, ScorpioBroker commented on Commons/src/main/java/eu/neclab/ngsildbroker/commons/tools/EntityTools.java
>  		if (attrNames == null || attrNames.isEmpty()) {
remove attrsNames check here (62-65) as it checks for the watchedAttributes which we shouldn't

2022-06-30 05:41 UTC, amitrnec commented on Commons/src/main/java/eu/neclab/ngsildbroker/commons/tools/EntityTools.java
> +		List<String> notifucationAttrs = subscription.getSubscription().getNotification().getAttributeNames();
Done

2022-06-30 05:41 UTC, amitrnec commented on Commons/src/main/java/eu/neclab/ngsildbroker/commons/tools/EntityTools.java
>  		if (attrNames == null || attrNames.isEmpty()) {
Removed

2022-06-30 06:36 UTC, ScorpioBroker approved these changes
lgtm

2022-06-30 06:40 UTC, merged