Fix issue no 329 and 330.
ScorpioBroker/ScorpioBroker pull request #332
Opened 2022-08-31 10:51 UTC by amitrnec

2022-09-14 10:25 UTC, ScorpioBroker requested changes
Please also provide a test for this changes

2022-09-14 10:25 UTC, ScorpioBroker commented on Commons/src/main/java/eu/neclab/ngsildbroker/commons/controllers/EntryControllerFunctions.java
> +				status = HttpStatus.CREATED;
This should be multi status. According to 6.15.3

2022-09-14 10:25 UTC, ScorpioBroker commented on Commons/src/main/java/eu/neclab/ngsildbroker/commons/controllers/EntryControllerFunctions.java
> +		if (result.getFails().isEmpty() && !result.getSuccess().isEmpty()) {
Only updated should still return an empty body. Add another check if reponsecode is 204 than no body shall be returned.

2022-09-27 04:51 UTC, vivekNEC approved these changes

2022-09-27 09:39 UTC, ScorpioBroker approved these changes
LGTM

2022-09-27 09:39 UTC, merged