fixed readiness issue for deployment
ScorpioBroker/ScorpioBroker pull request #346
Opened 2022-10-20 04:06 UTC by mohitNEC

2022-10-20 11:01 UTC, ScorpioBroker requested changes
Hi please use the new dockerhub structure 
so e.g. scorpiobroker/all-in-one-runner:spring-kafka-3.0.4 or scorpiobroker/subscription-manager:spring-kafka-3.0.4 
check here for the exact names of all components https://hub.docker.com/u/scorpiobroker but in general it's scorpiobroker/<all small letters and - component name>:spring-kafka-<version>

2022-11-10 03:37 UTC, mohitNEC commented
Review Comment Incorporated

2022-11-17 10:50 UTC, amitrnec approved these changes

2022-12-14 09:54 UTC, ScorpioBroker approved these changes

2022-12-14 10:05 UTC, merged