Vocab support
ScorpioBroker/ScorpioBroker pull request #440
Opened 2023-09-12 03:36 UTC by vivekNEC

2023-09-12 10:01 UTC, ScorpioBroker requested changes
lgtm just remove the sysout

2023-09-12 10:01 UTC, ScorpioBroker commented on Commons/src/main/java/com/github/jsonldjava/core/NGSIObject.java
> +			System.out.println("testing "+Constants.allowedScalars.get(payloadType).contains(expandedProperty));
remove

2023-09-12 13:54 UTC, ScorpioBroker approved these changes

2023-09-13 04:38 UTC, amitrnec commented on Commons/src/main/java/com/github/jsonldjava/core/NGSIObject.java
> +
Remove spec

2023-09-13 04:38 UTC, amitrnec commented on Commons/src/main/java/eu/neclab/ngsildbroker/commons/datatypes/terms/QQueryTerm.java
> +//				for (int i=0;i<tuple.size();i++){
Remove comment code.

2023-09-13 10:45 UTC, merged