Bugfix 524
ScorpioBroker/ScorpioBroker pull request #529
Opened 2024-02-16 03:54 UTC by brijeshnec

2024-02-16 05:21 UTC, amitrnec approved these changes

2024-02-29 10:25 UTC, ScorpioBroker requested changes

2024-02-29 10:25 UTC, ScorpioBroker commented on HistoryQueryManager/src/main/java/eu/neclab/ngsildbroker/historyquerymanager/repository/HistoryDAO.java
> +						+ NGSIConstants.NGSI_LD_HAS_VALUE + ",0," + NGSIConstants.JSON_LD_VALUE + "}') ::numeric ");
this doesn't quite work. unfortunately the test doesn't fail here but the max min gets cut for brandname=mercedes 
doing this aggr sql operations with only string values basically works with all types with have to support. please check if you can fix this after the sql call in java ... it's a bit wonkie but postgres is very "fragile" in this aggr functions so trying to fix this in sql might be a fruitless endeavor. 
brandName: {
  │     type: 'Property',
  │     distinctCount: [
  │       [
  │         1,
  │         '2022-09-10T13:21:24.000000Z',
  │         '2022-09-10T13:21:24.000000Z'
  │       ]
  │     ],
  │     totalCount: [
  │       [
  │         1,
  │         '2022-09-10T13:21:24.000000Z',
  │         '2022-09-10T13:21:24.000000Z'
  │       ]
  │     ]
  │   },

2024-03-13 10:11 UTC, ScorpioBroker approved these changes
lgtm

2024-03-13 10:11 UTC, merged