Geo josn error handling
ScorpioBroker/ScorpioBroker pull request #543
Opened 2024-03-15 03:32 UTC by brijeshnec

2024-03-15 11:45 UTC, amitrnec commented on Commons/src/main/java/eu/neclab/ngsildbroker/commons/tools/HttpUtils.java
> +				throw new ResponseException(ErrorType.NotAcceptable);
add message as well

2024-03-15 11:45 UTC, amitrnec commented on Commons/src/main/java/eu/neclab/ngsildbroker/commons/tools/HttpUtils.java
> +			throws JsonParseException, IOException, ResponseException {
remove JsonParseException, IOException because these are unused

2024-03-15 11:45 UTC, amitrnec commented on Commons/src/main/java/eu/neclab/ngsildbroker/commons/tools/HttpUtils.java
> +				logger.debug("exception in generateGeoJson ",e);
add filename as well

2024-03-15 11:45 UTC, amitrnec commented on Commons/src/main/java/eu/neclab/ngsildbroker/commons/tools/HttpUtils.java
> +			}catch (Exception e){
use response exception instead

2024-03-19 05:13 UTC, vivekNEC commented on Commons/src/main/java/eu/neclab/ngsildbroker/commons/tools/HttpUtils.java
> +				throw new ResponseException(ErrorType.NotAcceptable);
done

2024-03-19 05:13 UTC, vivekNEC commented on Commons/src/main/java/eu/neclab/ngsildbroker/commons/tools/HttpUtils.java
> +			throws JsonParseException, IOException, ResponseException {
done

2024-03-19 05:13 UTC, vivekNEC commented on Commons/src/main/java/eu/neclab/ngsildbroker/commons/tools/HttpUtils.java
> +				logger.debug("exception in generateGeoJson ",e);
done

2024-03-19 05:13 UTC, vivekNEC commented on Commons/src/main/java/eu/neclab/ngsildbroker/commons/tools/HttpUtils.java
> +			}catch (Exception e){
done

2024-03-22 05:59 UTC, amitrnec approved these changes

2024-04-23 14:58 UTC, ScorpioBroker requested changes
please resolve conflicts

2024-04-29 22:40 UTC, ScorpioBroker approved these changes

2024-04-29 22:40 UTC, merged