Broader localonly
ScorpioBroker/ScorpioBroker pull request #545
Opened 2024-03-21 06:51 UTC by brijeshnec

2024-03-22 05:58 UTC, amitrnec commented on HistoryQueryManager/src/main/java/eu/neclab/ngsildbroker/historyquerymanager/controller/HistoryController.java
> +		if (!localOnly && typeQuery == null && attrs == null && geometry == null && q == null) {
Validate this condition in all cases

2024-03-22 05:58 UTC, amitrnec commented on QueryManager/src/main/java/eu/neclab/ngsildbroker/queryhandler/controller/QueryController.java
> +		if (!localOnly && id == null && typeQuery == null && attrs == null && geometry == null && q == null && pick == null) {
Validate pick here

2024-03-26 04:59 UTC, brijeshnec commented on HistoryQueryManager/src/main/java/eu/neclab/ngsildbroker/historyquerymanager/controller/HistoryController.java
> +		if (!localOnly && typeQuery == null && attrs == null && geometry == null && q == null) {
done

2024-03-26 04:59 UTC, brijeshnec commented on QueryManager/src/main/java/eu/neclab/ngsildbroker/queryhandler/controller/QueryController.java
> +		if (!localOnly && id == null && typeQuery == null && attrs == null && geometry == null && q == null && pick == null) {
done

2024-04-12 08:43 UTC, ScorpioBroker requested changes
please update update test to be mergeable

2024-04-17 12:46 UTC, ScorpioBroker approved these changes

2024-04-17 12:46 UTC, merged